//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinhLuan
    {
        public string maBinhLuan { get; set; }
        public string maSanPham { get; set; }
        public string maTaiKhoan { get; set; }
        public string traLoi { get; set; }
        public System.DateTime Ngay { get; set; }
        public string noiDung { get; set; }
    }
}
