//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int maChiTietHoaDon { get; set; }
        public Nullable<int> maHoaDon { get; set; }
        public string maSanPham { get; set; }
        public Nullable<int> soLuong { get; set; }
        public Nullable<double> donGia { get; set; }
        public Nullable<double> ThanhTien { get; set; }
        public Nullable<int> giamGia { get; set; }
        public string TrangThai { get; set; }
    }
}
