//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int maHoaDon { get; set; }
        public Nullable<int> maTaiKhoan { get; set; }
        public string TenKhach { get; set; }
        public Nullable<System.DateTime> ngayMuaHang { get; set; }
        public string ghiChu { get; set; }
        public string SoDienThoai { get; set; }
        public string diaChi { get; set; }
        public string Email { get; set; }
    
        public virtual User User { get; set; }
    }
}
