//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string maHoaDon { get; set; }
        public string maTaiKhoan { get; set; }
        public string diaChiGiaoHang { get; set; }
        public string phuongThucThanhToan { get; set; }
        public Nullable<System.DateTime> ngayGiaoHang { get; set; }
        public Nullable<System.DateTime> ngayMuaHang { get; set; }
        public string tinhTrang { get; set; }
    }
}
