//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TaiKhoan
    {
        [Key]
        public string maTaiKhoan { get; set; }
        [Required (ErrorMessage ="Nhập Mật Khẩu ")]
        public string matKhau { get; set; }
        public string quyenTruyCap { get; set; }
        public string diaChi { get; set; }
        public string soDienThoai { get; set; }
        public Nullable<System.DateTime> ngaySinh { get; set; }
        public Nullable<long> gioiTinh { get; set; }
        public Nullable<long> tinhTrang { get; set; }
       
        [Required(ErrorMessage = "Nhập Tài Khoản Mail ")]
        public string Email { get; set; }
    }
}
