//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopBanHang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int maTaiKhoan { get; set; }
        public string Email { get; set; }
        public string matKhau { get; set; }
        public string diaChi { get; set; }
        public string soDienThoai { get; set; }
        public string gioiTinh { get; set; }
        public string Ten { get; set; }
        public Nullable<bool> xacThucEmail { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
    }
}
